### ISSUE TITLE
[Feat] : Marginal Error and element misconfigure from register page.

### ISSUE THREAD

**Issue by FashionFinds** [FashionFinds/FashionFinds-Web#3]
**Description**

Change the layout of the Register page with alignment to login page design.
Overflow of the elements in register page is towards the top, therefore looks after the marginal error
Remove the non-using input elements from the form.
Design the document title and icon as the home page.

![image](https://github.com/FashionFinds/FashionFinds-Web/assets/143785021/c06894df-72e1-416e-b370-e357b9eb9e9a)

**Comment by mohammaddanishshaikh** [comment]
I would like to work on this issue, can you please assign me

**Comment by FashionFinds** [comment]
PR is welcome
