### ISSUE TITLE
[Feat] : User Friendly add to cart notify

### ISSUE THREAD

**Issue by FashionFinds** [FashionFinds/FashionFinds-Web#6]
**Description**

Once the button of **Add to cart** clicks then an pop of alert appears on top.

![image](https://github.com/FashionFinds/FashionFinds-Web/assets/143785021/5e1bc1e5-9615-418d-ab7e-bbd573b571ef)

Proposed solution must contains the designed and well structure notifying system or just update the page without notifying.

2. Add the margin and padding for Responsiveness of the website. 
![Screenshot (219)](https://github.com/FashionFinds/FashionFinds-Web/assets/143785021/a326eb8b-6a08-4086-bb2d-06c49e5f65d2)

**Comment by KhushbuBonde** [comment]
I would like to work on this issue. Can you assign it?
